# -*- coding: utf-8 -*-
"""Voice_AI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11F1xLZM4mtjcBpH8zwyM-9S7ZfNUXeaE
"""

from transformers import pipeline

import warnings

def get_transcription(filename: str):

    warnings.filterwarnings('ignore')

    if type(filename) == str:

        pipe = pipeline("automatic-speech-recognition", model="Praveendecode/finetuned-whishper-small-marathi") # Load pre-trained model

        result = pipe(filename, generate_kwargs={"language": "marathi"}) # Get transcription result

        transcription = result['text']

        return transcription

    else:
        raise ValueError('Provide a valid filename')

"""

```
# Note : Download colab files as .py script
```

"""